title: 歷史三兩事
description: 看圖說故事
lang: zh-TW
baseurl: "/historysnaps-blog"
url: "https://VictorKerrye.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /posts/:year/:month/:day/:title/
